spring.application.name=agendador

spring.datasource.url=jdbc:postgresql://localhost:5432/agendador
spring.datasource.username=agendador
spring.datasource.password=agendador

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

agendador.jwt.secret=${JWT_SECRET:chave-local-de-desenvolvimento-nao-use-em-producao}
agendador.usuario-inicial.login=${ADMIN_LOGIN:admin}
agendador.usuario-inicial.senha=${ADMIN_SENHA:admin123}
